# Jekyll configuration

name: nino
description: 昔我往期，杨柳依依

# url is currently only used only for the RSS feed in feed.xml
url: "https://iring.fun"

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""
pageurl: "/pages"
downloadurl: "/attachments"

# CDN 对应的域名
cdn:
  base: "https://jekyll-1251110281.file.myqcloud.com"
  # 放置不需要验证Host和Refer的附件，可以直接使用wget命令
  gen: "https://jekyll-gen-1251110281.file.myqcloud.com"
  # 放置katex插件的js，css以及字体文件
  katex: "https://jekyll-1251110281.file.myqcloud.com/katex"
  image: "https://jekyll-1251110281.file.myqcloud.com/images"
  # 放置一些需要验证Host和Refer的附件
  css: "https://jekyll-1251110281.file.myqcloud.com/css"
  js: "https://jekyll-1251110281.file.myqcloud.com/js"
  fonts: "https://jekyll-1251110281.file.myqcloud.com/fonts"
  attachments: "https://jekyll-1251W110281.file.myqcloud.com/attachments"

# These can be '' to hide the Github or Gitlab nav buttons
# github: 'rusterx/osier'
github: "rusterx/rusterx.github.io"
gitlab: ""
# gitee: 'https://gitee.com/rusterx'
gitee: ""
# coding: 'https://nino.coding.net/user'
coding: ""
# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ""

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ""

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ""

permalink: /:year/:month/:title:output_ext
# permalink: /:categories/:title
output_ext: ".html"
highlighter: rouge
markdown: kramdown

# jekyll v3.0
# gems: ['jekyll-paginate']

# jekyll v4.0
plugins: ["jekyll-paginate"]

paginate: 5
exclude: ["README.md", "LICENSE"]
theme: jekyll-theme-minimal

# set custom website title
scope:
  type: "posts"
values:
  layout: "post"
  title: ""
